### PR TITLE
use correct/new repo

### PR DESCRIPTION
**Pull request by MarnixCroes**
should fix https://github.com/WalletWasabi/WasabiDoc/pull/1730

### CODE REVIEW

**Review by yahiheb — APPROVED** [review]
LGTM

> should fix https://github.com/WalletWasabi/WasabiDoc/pull/1728

You meant to say #1730

**Comment by MarnixCroes** [comment]
updated my comment, 1ms before you commented :D

**Comment by yahiheb** [comment]
Let's see if this fixes the deployment issue. If not let's open it again.

**Comment by yahiheb** [comment]
This didn't work, I will open the issue again.

**Pull request merged**
